name: Auto Thank You for Issues
on:
  issues:
    types:
      - opened

jobs:
  to-the-steps:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TOKEN: ${{secrets.TOKEN}}
      TOKEN2: ${{vars.TOKEN}}

    steps:
      - name: GITHUB_TOKEN
        run: echo "TOKEN -> $GITHUB_TOKEN"

      - name: TOKEN
        run: echo "TOKEN -> $TOKEN"

      - name: VARS TOKEN
        run: echo "TOKEN -> $TOKEN2"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm install typescript  # Install TypeScript
          npm install            # Install other dependencies

      - name: Run TypeScript script
        run: npx ts-node .github/workflows/autoty.ts
