name: Auto Thank You for Issues
on:
  issues:
    types:
      - opened

jobs:
  to-the-steps:
    runs-on: ubuntu-latest
    steps:
      - name: try envi
        run: echo "Value -> ${{vars.TESTSECRET}} "

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Set the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm install typescript  # Install TypeScript
          npm install            # Install other dependencies

      - name: Run TypeScript script
        run: npx ts-node .github/workflows/autoty.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
