name: Auto Thank You for Issues
on:
  issues:
    types:
      - opened

jobs:
  thank-you:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        run: |
          ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
          COMMENT="Thank you for creating this issue! We appreciate your feedback. 👍\n\nIf you have any questions or need further assistance, feel free to ask."
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER}/comments"
          RESPONSE=$(curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$COMMENT\"}" "$URL")
          echo "Comment response: $RESPONSE"
